In [12]:
import numpy as np

In [13]:
grid = np.zeros((4, 4))
new_vals = 0
while new_vals < 2:
    val = np.random.choice([2, 4])
    i = np.random.randint(0, 3)
    j = np.random.randint(0, 3)
    if grid[i, j] == 0:
        grid[i, j] = val
        new_vals += 1

In [14]:
grid

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [2., 0., 4., 0.],
       [0., 0., 0., 0.]])

In [28]:
def slide(arr, dir):
    """
    [slide] slides and combines the numbers in [arr] in the direction
    [dir] with the following rules:
    1. if dir is 1, then slide and combine numbers to the left
    2. if dir is -1, slide and combine numbers to the right
    3. numbers can be combined only if they are slid into a block with the same
    value (i.e. 2 -> 2 becomes 4, 4->4 becomes 8, 2->4 does not combine)
    4. Numbers can only be combined once in a slide (4->4->8 is 4->8 not 16)
    5. Numbers are slide such that no gaps exist in the row and all numbers have been slide
    or combined
    
    Steps:
    1. flip array if dir is -1
    2. loop through each element
        a. find spot to slide to (spot to combine with or with next 0)
    """
    if dir == -1:
        temp = np.flip(np.copy(arr))
    else:
        temp = np.copy(arr)
    #For each element (after the 0th)
    combined = [False]*len(temp) #tracks which positions have been combined
    for i in range(1, len(temp)):
        
        if temp[i] == 0: continue
        
        #Finds next spot with next nonzero or 0th index
        idx = i-1
        while idx > 0 and temp[idx] == 0:
            idx -= 1
        
        if temp[idx] != 0 and temp[idx] != temp[i]:
            idx += 1
        
        if idx == i: continue

        if temp[idx] == temp[i] and not combined[idx]:
            #then combine
            temp[idx] = temp[idx] * 2
            temp[i] = 0
            combined[idx] = True
        elif temp[idx] == 0:
            #Slide number
            temp[idx] = temp[i]
            temp[i] = 0
        
        print(idx, temp)
    
    return np.flip(temp) if dir == -1 else temp

In [29]:
print(slide([4,2,2,0], dir=1))
print("This should print: [4,4,0,0]")

1 [4 4 0 0]
[4 4 0 0]
This should print: [4,4,0,0]


In [30]:
print(slide([2,2,2,2], dir=1))
print("This should print: [4,4,0,0]")

0 [4 0 2 2]
1 [4 2 0 2]
1 [4 4 0 0]
[4 4 0 0]
This should print: [4,4,0,0]
